# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              primary_key=True, serialize=False,
                                              to=settings.AUTH_USER_MODEL)),
                ('atwork', models.BooleanField(default=False))
            ],
        ),
    ]
