# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160528_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtWork',
            new_name='Location',
        ),
    ]
