# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160805_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='manual_registry',
            field=models.BooleanField(default=False),
        ),
    ]
