# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gerencex.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_timing_manual_registry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restday',
            options={'ordering': ['date'], 'verbose_name': 'dia não útil', 'verbose_name_plural': 'dias não úteis'},
        ),
        migrations.AlterModelOptions(
            name='timing',
            options={'ordering': ['-date_time'], 'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
        migrations.RemoveField(
            model_name='timing',
            name='manual_registry',
        ),
        migrations.AddField(
            model_name='timing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restday',
            name='date',
            field=models.DateField(help_text='Formato DD/MM/AAAA', unique_for_date=True, validators=[gerencex.core.validators.validate_date], verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
