# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160528_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='UserDetail',
        ),
    ]
