# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160812_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timing',
            options={'ordering': ['date_time'], 'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
    ]
