# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160529_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='at_work',
            new_name='atwork',
        ),
    ]
