# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160813_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timing',
            options={'ordering': ['date_time'], 'verbose_name': 'registro de entrada e saída', 'verbose_name_plural': 'registros de entrada e saída'},
        ),
    ]
