# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restday_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restday',
            name='work_hours',
            field=models.DurationField(default=0, verbose_name='carga horária'),
        ),
    ]
