# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import gerencex


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restday_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restday',
            name='date',
            field=models.DateField(help_text='Formato DD/MM/AAAA',
                                   unique=True,
                                   validators=[gerencex.core.validators.validate_date],
                                   verbose_name='data'),
        ),
    ]
