# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import gerencex.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160818_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restday',
            name='date',
            field=models.DateField(help_text='Formato DD/MM/AAAA', unique=True, validators=[gerencex.core.validators.validate_date], verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='restday',
            name='work_hours',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='carga horária'),
        ),
    ]
