# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 21:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20160818_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('credit', models.DurationField(verbose_name='crédito')),
                ('debit', models.DurationField(default=datetime.timedelta(0, 25200), verbose_name='débito')),
                ('daily_balance', models.DurationField(verbose_name='saldo diário')),
                ('total_balance', models.DurationField(verbose_name='saldo acumulado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'banco de horas',
                'get_latest_by': 'date',
                'ordering': ['date', 'user'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hoursbalance',
            unique_together=set([('date', 'user')]),
        ),
        migrations.AlterIndexTogether(
            name='hoursbalance',
            index_together=set([('date', 'user')]),
        ),
    ]
