# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160821_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoursbalance',
            options={'get_latest_by': 'date', 'ordering': ['date', 'user'], 'verbose_name': 'banco de horas', 'verbose_name_plural': 'banco de horas'},
        ),
    ]
