# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160821_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursbalance',
            name='balance',
            field=models.IntegerField(default=-7, verbose_name='saldo acumulado'),
        ),
        migrations.AlterField(
            model_name='hoursbalance',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='crédito'),
        ),
    ]
