# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160821_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoursbalance',
            old_name='total_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='hoursbalance',
            name='daily_balance',
        ),
    ]
