# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20160902_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('cause', models.CharField(choices=[('CR', 'Curso'), ('CD', 'Cedido para outra unidade'), ('IN', 'Inspeção'), ('FR', 'Período de férias (formal)'), ('LM', 'Licença médica'), ('LP', 'Licença-prêmio'), ('LA', 'Licença para atividade política'), ('GR', 'Gozo do recesso (formal)'), ('OU', 'Outros afastamentos')], default='FR', max_length=2, verbose_name='motivo')),
                ('credit', models.IntegerField(verbose_name='crédito')),
                ('debit', models.IntegerField(verbose_name='débito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
