# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160826_0253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hoursbalance',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='hoursbalance',
            index_together=set([]),
        ),
    ]
