# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_absences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absences',
            options={'get_latest_by': 'date', 'ordering': ['date', 'user'], 'verbose_name': 'Afastamento', 'verbose_name_plural': 'Afastamentos'},
        ),
        migrations.AlterUniqueTogether(
            name='absences',
            unique_together=set([('date', 'user')]),
        ),
        migrations.AlterIndexTogether(
            name='absences',
            index_together=set([('date', 'user')]),
        ),
    ]
