# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160827_0113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hoursbalance',
            unique_together=set([('date', 'user')]),
        ),
        migrations.AlterIndexTogether(
            name='hoursbalance',
            index_together=set([('date', 'user')]),
        ),
    ]
