# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160923_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absences',
            options={'get_latest_by': 'date', 'ordering': ['user', '-date'], 'verbose_name': 'Afastamento', 'verbose_name_plural': 'Afastamentos'},
        ),
    ]
