# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160923_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absences',
            name='cause',
            field=models.CharField(choices=[('CR', 'Curso'), ('CD', 'Cedido para outra unidade'), ('IN', 'Inspeção'), ('FR', 'Férias (formal)'), ('LM', 'Licença médica'), ('LP', 'Licença-prêmio'), ('LA', 'Licença para atividade política'), ('GR', 'Gozo do recesso (formal)'), ('OU', 'Outros afastamentos')], default='FR', max_length=2, verbose_name='motivo'),
        ),
        migrations.AlterField(
            model_name='absences',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='crédito'),
        ),
        migrations.AlterField(
            model_name='absences',
            name='debit',
            field=models.IntegerField(default=0, verbose_name='débito'),
        ),
    ]
