# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 13:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160924_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('initials', models.CharField(max_length=15, verbose_name='sigla')),
                ('active', models.BooleanField(default=True, verbose_name='unidade ativa')),
                ('regular_work_hours', models.DurationField(default=datetime.timedelta(0, 25200), verbose_name='jornada diária')),
                ('max_daily_credit', models.BooleanField(default=False, verbose_name='restrição de jornada diária máxima')),
                ('max_daily_credit_value', models.DurationField(default=datetime.timedelta(0, 36000), verbose_name='restrição de valor da máxima jornada diária')),
                ('max_monthly_balance', models.BooleanField(default=False, verbose_name='restrição de saldo mensal máximo de horas')),
                ('max_monthly_balance_value', models.DurationField(default=datetime.timedelta(0, 72000), verbose_name='valor do saldo mensal máximo')),
                ('min_checkin_time', models.BooleanField(default=False, verbose_name='restrição de horário mínimo para entrada')),
                ('min_checkin_time_value', models.TimeField(default=datetime.time(8, 0), verbose_name='horário mínimo para entrada')),
                ('max_checkout_time', models.BooleanField(default=False, verbose_name='restrição de horário máximo para saída')),
                ('max_checkout_time_value', models.TimeField(default=datetime.time(20, 0), verbose_name='horário máximo para saída')),
                ('checkin_tolerance', models.DurationField(default=datetime.timedelta(-1, 85800), verbose_name='tolerância para entrada')),
                ('checkout_tolerance', models.DurationField(default=datetime.timedelta(0, 300), verbose_name='tolerância para saída')),
            ],
        ),
        migrations.AlterField(
            model_name='absences',
            name='cause',
            field=models.CharField(choices=[('CR', 'Curso'), ('CD', 'Cedido para outra unidade'), ('IN', 'Inspeção'), ('FR', 'Férias (formal)'), ('LM', 'Licença médica'), ('LP', 'Licença-prêmio'), ('LA', 'Licença para atividade política'), ('GR', 'Gozo do recesso (formal)'), ('FT', 'Falta não justificada'), ('OU', 'Outros afastamentos')], default='FR', max_length=2, verbose_name='motivo'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.Office'),
        ),
    ]
