# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20161011_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='nome',
            new_name='name',
        ),
    ]
