# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161012_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['initials'], 'verbose_name': 'Lotação', 'verbose_name_plural': 'Lotações'},
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='office',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='core.Office'),
        ),
    ]
