# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20161013_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='hours_control_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de início do banco de horas'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='opening_hours_balance',
            field=models.IntegerField(default=0, verbose_name='saldo inicial'),
        ),
    ]
