# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_office_last_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='client_ip',
            field=models.CharField(default='xxx.xxx.xxx.xxx', max_length=15, verbose_name='ip do cliente'),
        ),
        migrations.AddField(
            model_name='timing',
            name='client_local_ip',
            field=models.CharField(default='xxx.xxx.xxx.xxx', max_length=15, verbose_name='ip local do cliente'),
        ),
    ]
