# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20161108_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='client_ip',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='ip do cliente'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='client_local_ip',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='ip local do cliente'),
        ),
    ]
