# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20161108_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='min_work_hours_for_credit',
            field=models.DurationField(default=datetime.timedelta(0, 25200), verbose_name='jornada diária necessária para acumular crédito'),
        ),
    ]
