# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20161110_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='min_work_hours_for_credit',
            field=models.BooleanField(default=True, verbose_name='restrição de jornada diária necessária para acumular créditos'),
        ),
    ]
