# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_office_linked_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='linked_to',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='linkedin', to='core.Office'),
        ),
    ]
