# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20161207_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absences',
            name='cause',
            field=models.CharField(choices=[('CR', 'Curso'), ('CD', 'Cedido para outra unidade'), ('IN', 'Inspeção'), ('FR', 'Férias (formal)'), ('LM', 'Licença médica'), ('LP', 'Licença-prêmio'), ('LA', 'Licença para atividade política'), ('GR', 'Gozo do recesso (formal)'), ('FT', 'Falta não justificada'), ('RE', 'Recesso regimental'), ('OU', 'Outros afastamentos')], default='FR', max_length=2, verbose_name='motivo'),
        ),
    ]
